### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by JimBobSquarePants** [campaignmonitor/createsend-dotnet#33]
There's very little in the repo and the API documentation does not even show an example for how to add a subscriber to a list.

https://www.campaignmonitor.com/api/getting-started/

**Comment by mjwills** [comment]
I love the Archer avatar!

You may find https://www.campaignmonitor.com/api/subscribers/ and https://github.com/campaignmonitor/createsend-dotnet/blob/master/Samples/Subscriber.cs helpful. Do they cover what you need?

**Comment by JimBobSquarePants** [comment]
Thanks! Yeah that was a great help. Much appreciated.
