### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by nblumhardt** [campaignmonitor/createsend-dotnet#41]
Hi! We're in the process of moving some infrastructure to .NET Core/Linux. Any ETA on platform support? Thanks!

**Comment by hhovind** [comment]
+1

**Comment by hhovind** [comment]
Any updates on this?

**Comment by asadighi** [comment]
Hi, Thank you for your request. We are very interested to have this support; however, we are currently focused on other areas of APIs and Integrations.  In the meantime, we would be more than happy to review and merge any pull requests that facilitates this change.

**Comment by CruelMoney** [comment]
+1

**Comment by Izzmo** [comment]
I've created a branch to target .NET Standard 1.6. Can't got 1.5 or earlier as System.Web and some other framework namespaces weren't available yet. It is located at https://github.com/Izzmo/createsend-dotnet.

I plan on opening a formal PR soon, which hopefully Campaign Monitor will push through and up to NuGet.

If you are just sending regular transaction emails and not having to deal with rate limiting, I would highly suggest you abandon the NuGet package and develop your own WebClient or WebRequest wrapper to do it as then you aren't relying on an outdated dependency.

**Comment by mattgenious** [comment]
Hello @niawahyuni can we please have official support for .net standard 2.0?

**Comment by edgunn** [comment]
.NET Standard 2.0 is now officially supported as of v5.2.0, apologies for the far too long delay!
Any issues please let me know
