### ISSUE TITLE
No support to .NetCore

### ISSUE THREAD

**Issue by Xamarians** [campaignmonitor/createsend-dotnet#53]
I'd tried to install it in .Net Core Web Api but seems it doesn't support it. Is there any way to use this library in .NET Core?

**Comment by JanKolk** [comment]
@Xamarians Are you using .netcore 2.0? I created a pull request thats supports 2.0 (#55)

**Comment by nblumhardt** [comment]
Dupe of #41. Great to see a PR up, @JanKolk!!! :-)

**Comment by JanKolk** [comment]
@nblumhardt I released a version to [nuget](https://www.nuget.org/packages/campaignmonitor-api-dotnet-standard) until the pull request is merged.

**Comment by mattgenious** [comment]
Hello @niawahyuni can we please have official support for .net standard 2.0?

**Comment by edgunn** [comment]
.NET Standard 2.0 is now officially supported as of v5.2.0, apologies for the far too long delay!
Any issues please let me know
