### ISSUE TITLE
Is this library already supporting TLSv1.2?

### ISSUE THREAD

**Issue by dra-nozebra** [campaignmonitor/createsend-dotnet#64]
Hello,

Campaign Monitor has recently informed all their users that they'll drop support for TLSv1.0 and TLSv1.1. This means that our implementations must be upgraded in order to support TLSv1.2.

We have a couple of projects currently using the createsend-dotnet package for Campaign Monitor implementation. Is the package already supporting TLSv1.2? If not, are there plans for this, or any recommended alternative?

Thanks in advance,

dra

**Comment by markstaples** [comment]
Hi @dra-nozebra 

The current version of this package does support TLSv1.2. This can be tested using the following test endpoint https://tlsv12.api.createsend.com which only accepts TLSv1.2 connections. Feel free to use this test endpoint to validate that your integrations and packages connect okay with the Campaign Monitor API - please note that the test endpoint will be removed after the cut over date.

Cheers,

Mark.

**Comment by dra-nozebra** [comment]
@markstaples are you just able to confirm to me, from which version has TLSv1.2 been supported?
Thanks in advance!

**Comment by markstaples** [comment]
We can confirm that we'll be supporting the following set of cipher suites on our server.

-  TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
-  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
-  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
-  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
-  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
-  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

You can also refer to https://www.ssllabs.com/ssltest/analyze.html?d=tlsv12.api.createsend.com&hideResults=on for reference.

Hope this answers you question.

**Comment by dra-nozebra** [comment]
Sorry, I meant at which version of the package was TLSv1.2 implemented? I'm currently running an old version of it (4.2) and I wanted to understand which minimum version should I upgrade the package to in order to support TLSv1.2 in my implementation.

**Comment by markstaples** [comment]
Ah, misread that one @dra-nozebra. We've only validated that the latest version of the package works against TLSv1.2, but you can test previous versions of the packages by updating the endpoint to https://tlsv12.api.createsend.com or modifying via hosts file.
