### ISSUE TITLE
Version 4.2.2 already supporting TLS1.2?

### ISSUE THREAD

**Issue by aaryan79831014** [campaignmonitor/createsend-dotnet#66]
Hi Team,

   We are using version 4.2.2 and using API Key authentication method to interact with Campaign Monitor. I read other issue raised for the TLS 1.2 support compatibility (https://github.com/campaignmonitor/createsend-dotnet/issues/64). 
I cannot find an answer to see if the version 4.2.2 is already compatible. 
When tried to force the endpoint to(https://tlsv12.api.createsend.com), getting connection closed error.
Can you please confirm if version 4.2.2 is already supporting TLS1.2?

Thanks,

**Comment by markstaples** [comment]
Hi @aaryan79831014 

We've only validated that the latest version of the package works against TLSv1.2, but you can test previous versions of the packages by updating the endpoint to https://tlsv12.api.createsend.com or modifying via hosts file.

Cheers,

**Comment by aaryan79831014** [comment]
Thanks @markstaples .
